#!/bin/sh
set -e

tiddlywiki_script=$(readlink -f $(which tiddlywiki))

if [ -n "$NODE_MEM" ]; then
    # Based on rule of thumb from:
    # http://fiznool.com/blog/2016/10/01/running-a-node-dot-js-app-in-a-low-memory-environment/
    mem_node_old_space=$((($NODE_MEM*4)/5))
    NODEJS_V8_ARGS="--max_old_space_size=$mem_node_old_space $NODEJS_V8_ARGS"
fi

if [ ! -d /var/lib/tiddlywiki/mywiki ]; then
  /usr/bin/env node $NODEJS_V8_ARGS $tiddlywiki_script mywiki --init server

  mkdir /var/lib/tiddlywiki/mywiki/tiddlers
fi


# Configure the tiddlywiki to be served on a path if it is given
WEBHOST_TID=/var/lib/tiddlywiki/mywiki/tiddlers/\$__config_tiddlyweb_host.tid
if [ -n "${SERVE_URI}" ]; then
  cp /tiddlyweb_host_template ${WEBHOST_TID}
  echo '$protocol$//$host$'${SERVE_URI}"/" >> ${WEBHOST_TID}
  echo "tiddlywiki will be served at ${SERVE_URI}"
else
  if [ -e ${WEBHOST_TID} ]; then
    rm ${WEBHOST_TID}
  fi
fi

OPTIONAL_PARAMS=""
# set prefix if not emptystring
if [ ! -z "${SERVE_URI:+x}" ]; then
  echo "Setting path-prefix to $SERVE_URI"
  OPTIONAL_PARAMS="$OPTIONAL_PARAMS path-prefix=\"$SERVE_URI\""
fi

# set authenticated-user-header if not emptystring
if [ ! -z "${X_AUTH_HEADER:+x}" ]; then
  echo "Setting authenticated-user-header to $X_AUTH_HEADER"
  OPTIONAL_PARAMS="$OPTIONAL_PARAMS authenticated-user-header=\"$X_AUTH_HEADER\""
fi

# set port if not emptystring
if [ ! -z "${PORT:+x}" ]; then
  echo "Setting port to $PORT"
  OPTIONAL_PARAMS="$OPTIONAL_PARAMS port=$PORT"
fi

# set username if not emptystring, set password if set (allows empty password)
if [ ! -z "${USERNAME:+x}" ]; then
  echo "Setting username to $USERNAME"
  echo "Setting password to \"${PASSWORD-wiki}\""
  OPTIONAL_PARAMS="$OPTIONAL_PARAMS username=\"$USERNAME\" password=\"${PASSWORD-wiki}\""
fi

# Start the tiddlywiki server
if [ ! -z "${OPTIONAL_PARAMS}" ]; then
  echo "Running with parameters: ${OPTIONAL_PARAMS}"
fi
exec /usr/bin/env node $NODEJS_V8_ARGS $tiddlywiki_script mywiki --listen host=0.0.0.0 root-tiddler="$:/core/save/all" root-render-type="text/plain" root-serve-type="text/html" $OPTIONAL_PARAMS
